# Build Stage
FROM maven:latest AS builder
WORKDIR /app
COPY . .
RUN ["mvn", "clean", "package", "-DskipTests"]

# Runtime Stage
FROM openjdk:21
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8443

ENV SPRING_PROFILES_ACTIVE=prod

CMD ["java", "-jar", "app.jar"]